name: Release Tauri
on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true
      update_description:
        description: Release changelog
        required: true
jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Node.js setup
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: Install app dependencies
        run: yarn

      - name: Build the app
        uses: tauri-apps/tauri-action@v0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v${{ github.event.inputs.update_description }} 
          releaseName: v${{ github.event.inputs.version }}
          releaseBody: ${{ github.event.inputs.update_description }}
          releaseDraft: true
          prerelease: false
